cache: bundler

language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head

script: 'bundle exec rake'

before_install: gem install bundler -v 1.10.6

notifications:
  email:
    recipients:
      - michelangelo93@gmail.com
    on_failure: change
    on_success: never